<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-TIC5DM4" ignored="0" name="Test" tests="2" failures="1" timestamp="2024-08-26T11:59:35 IST" time="30.868" errors="0">
  <testcase name="runScenario" time="14.182" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="16.234" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]
at com.App.Testcases.InvalidTest.he_enters_the_in_valid_details(InvalidTest.java:31)
at âœ½.he enters the in valid details(file:///C:/Users/Administrator/eclipse-workspace/CucumberDemoWeb/src/test/resources/features/back.feature:9)
... Removed 5 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
