<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="7"
           failures="1"
           errors="0"
           skipped="0"
           time="77.315">
  <properties />
            <testcase name="runScenario" time="10.509" classname="com.App.Testcases.testrunner">
                <failure type="java.lang.AssertionError"
                  message="Login Failed expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]"
              >
<![CDATA[java.lang.AssertionError: Login Failed expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.assertEqualsImpl(Assert.java:136)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:575)
  com.App.Testcases.loginTestCase.he_enters_and(loginTestCase.java:40)
  âœ½.he enters "pathanasifkhan461@gmail.com" and "Assm@7866"(file:///C:/Users/Administrator/eclipse-workspace/Cucumber_DemoWebshop/src/test/resources/features/login.feature:6)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="runScenario" time="12.242" classname="com.App.Testcases.testrunner" />
                <testcase name="runScenario" time="12.442" classname="com.App.Testcases.testrunner" />
                <testcase name="runScenario" time="7.618" classname="com.App.Testcases.testrunner" />
                <testcase name="runScenario" time="12.866" classname="com.App.Testcases.testrunner" />
                <testcase name="runScenario" time="9.181" classname="com.App.Testcases.testrunner" />
                <testcase name="runScenario" time="12.457" classname="com.App.Testcases.testrunner" />
      
</testsuite>
